#!/usr/bin/env bash

set -e -o pipefail

function show_help(){
    echo  "USAGE: $0 [category_of_news] [--help]"
    echo  "OPTIONS:"
    echo -e "\n--help   Display this help message"
    echo "Categories to choose from:"
    echo -e "\t\tmountaineering\n\t\texpeditions\n\t\tpolar-exploration\n\t\tlong-distance-trekking\n\t\t8000ers"
    exit 0
}

while getopts ":h" opt; do
    case $opt in
        h)
            show_help 
            ;;
        \?)
            echo "Invalid option: ${OPTARG}" >&2 
            exit 1
            ;;
    esac
done   

if [[ -z "$1" ]]; then
    echo "No Category provided...defaulting to category: \"mountaineering\"..."
    CATEGORY="mountaineering"
else
    echo "Searching for news in category: \"$1\"..."
    CATEGORY="$1"
fi

LOWER_CATEGORY="${CATEGORY,,}"

case $LOWER_CATEGORY in
    mountaineering)
        :
        ;;
    expeditions)
        :
        ;;
    polar-exploration)
        :
        ;;
    long-distance-trekking)
        :
        ;;
    8000ers)
        :
        ;;
    *)
        echo "Invalide choice...Exiting"
        exit 1
        ;;
esac

TERMINAL_WIDTH="$(tput cols)"
PADDING=""
echo "Checking for news in category: ${LOWER_CATEGORY}..."
echo

RANDOM_NUMBER="${RANDOM}" 
WEBSITE="https://explorersweb.com"
URL_FOR_NEWS="${WEBSITE}/category/${LOWER_CATEGORY}/"
PATTERN="${URL_FOR_NEWS%*/*/*/}"

function pick_news(){
    local NUMBER_PATTERN_1="^[0-9]$"
    local NUMBER_PATTERN_2="^[0-9]{2}$"
    local QUIT_PATTERN="^[qQ]$"
    echo
    read -p "Enter the number for the article you would like to read (or press q to quit) " -n 2 -r
    echo
    if [[ $REPLY =~ ${QUIT_PATTERN} ]]; then
        exit 0
    fi
    # Check if it matches pattern , then continue next else just exit out
    [[ $REPLY =~ ${NUMBER_PATTERN_1} ]] || [[ $REPLY =~ ${NUMBER_PATTERN_2} ]] || echo "Pattern not matched..."
    
    local NEWS="$(cat "/tmp/news-${RANDOM_NUMBER}" | head -n $REPLY | tail -n 1 | awk -F'\t' '{print "https://explorersweb.com/"$NF}' | \
                  xargs -I{} -- 2>/dev/null curl {} | \
                  grep --only-matching -e '<p>.*</p>' -e '<title>.*</title>' | ghead -n -3 | pandoc -f html -t plain || \
                  cat "/tmp/news-${RANDOM_NUMBER}" | head -n $REPLY | tail -n 1 | awk -F'\t' '{print "https://explorersweb.com/"$NF}' | \
                  xargs -I{} -- 2>/dev/null curl {} | \
                  grep --only-matching -e '<p>.*</p>' -e '<title>.*</title>' | head -n -3 | pandoc -f html -t plain || \
                  echo "Cannot find entered number...." 1>&2)" 
    
    local FIRST_LINE=$(echo "$NEWS" | head -1)
    local EXCEPT_FIRST_LINE=$(echo "$NEWS" | tail -n +2)
    local SPACES=$(( (TERMINAL_WIDTH - ${#FIRST_LINE}) / 2 ))  
    for (( i=0; i<$SPACES; i++ )); do
        PADDING+=" "
    done
    printf "%s%s\n%s" "${PADDING}" "${FIRST_LINE}" "${EXCEPT_FIRST_LINE}"  | fmt -w ${TERMINAL_WIDTH} | less
}

function display_news(){
    declare -i COUNT
    local COMMAND="$(2>/dev/null curl "${URL_FOR_NEWS}" \
        | pandoc -t plain | grep -A1 -i -e '<div class="news-card">' \
        | grep -v -e'<div class="news-card">' | grep -e "${PATTERN}" \
        | awk -F\" '{print $2}')" 
    local COUNT=1
    while read -r LINE; do
        local TITLE="$(echo "${LINE}" | awk -F/ '{print $4}')"
        echo -e ""${COUNT}"\t"${TITLE}"" | tee -a "/tmp/news-${RANDOM_NUMBER}"
        COUNT=$COUNT+1
    done < <(echo "${COMMAND}")
    pick_news
}

function main(){
    display_news
}

function cleanup(){
    rm "/tmp/news-${RANDOM_NUMBER}"
}

main
trap cleanup EXIT
